### PR TITLE
introduce pronounciation guide

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by yocontra** [comment]
@rvagg Did you sign the [jif CLA](http://hehe.cool)?

**Comment by rvagg** [comment]
Of course. CLA

**Comment by sashahart** [comment]
This is a big problem for us. We are a big enterprise shop, and we would like to pronounce it "skippy." I'm afraid that unless this obvious oversight is addressed, we will be forced to fork the project.

**Comment by rvagg** [comment]
Perhaps we can consider a dual-licensing scheme that allows for the use of "skippy", `/skɪpi/`, in limited circumstances.

**Pull request closed without merging**
